/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BattleFinishRequest,
  BattleRewardResponse,
  BattleStartRequest,
  BattleStartResponse,
  ErrorResponse,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type startBattleResponse200 = {
  data: BattleStartResponse
  status: 200
}

export type startBattleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type startBattleResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startBattleResponseSuccess = (startBattleResponse200) & {
  headers: Headers;
};
export type startBattleResponseError = (startBattleResponse401 | startBattleResponse404) & {
  headers: Headers;
};

export type startBattleResponse = (startBattleResponseSuccess | startBattleResponseError)

export const getStartBattleUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/battles/start`
}

/**
 * @summary バトル開始（モンスター図鑑未登録なら自動登録）
 */
export const startBattle = async (battleStartRequest: BattleStartRequest, options?: RequestInit): Promise<startBattleResponse> => {

  const res = await fetch(getStartBattleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(battleStartRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: startBattleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startBattleResponse
}




export const getStartBattleMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BattleStartRequest }) => {
    return startBattle(arg, options);
  }
}
export const getStartBattleMutationKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/battles/start`] as const;

export type StartBattleMutationResult = NonNullable<Awaited<ReturnType<typeof startBattle>>>

/**
 * @summary バトル開始（モンスター図鑑未登録なら自動登録）
 */
export const useStartBattle = <TError = Promise<UnauthorizedResponse | ErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof startBattle>>, TError, Key, BattleStartRequest, Awaited<ReturnType<typeof startBattle>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getStartBattleMutationKey();
  const swrFn = getStartBattleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type finishBattleResponse200 = {
  data: BattleRewardResponse
  status: 200
}

export type finishBattleResponse400 = {
  data: ErrorResponse
  status: 400
}

export type finishBattleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type finishBattleResponseSuccess = (finishBattleResponse200) & {
  headers: Headers;
};
export type finishBattleResponseError = (finishBattleResponse400 | finishBattleResponse401) & {
  headers: Headers;
};

export type finishBattleResponse = (finishBattleResponseSuccess | finishBattleResponseError)

export const getFinishBattleUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/battles/finish`
}

/**
 * @summary バトル終了
 */
export const finishBattle = async (battleFinishRequest: BattleFinishRequest, options?: RequestInit): Promise<finishBattleResponse> => {

  const res = await fetch(getFinishBattleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(battleFinishRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: finishBattleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as finishBattleResponse
}




export const getFinishBattleMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BattleFinishRequest }) => {
    return finishBattle(arg, options);
  }
}
export const getFinishBattleMutationKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/battles/finish`] as const;

export type FinishBattleMutationResult = NonNullable<Awaited<ReturnType<typeof finishBattle>>>

/**
 * @summary バトル終了
 */
export const useFinishBattle = <TError = Promise<ErrorResponse | UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof finishBattle>>, TError, Key, BattleFinishRequest, Awaited<ReturnType<typeof finishBattle>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFinishBattleMutationKey();
  const swrFn = getFinishBattleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
