/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GameStartRequest,
  StartGame200,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type startGameResponse200 = {
  data: StartGame200
  status: 200
}

export type startGameResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type startGameResponseSuccess = (startGameResponse200) & {
  headers: Headers;
};
export type startGameResponseError = (startGameResponse401) & {
  headers: Headers;
};

export type startGameResponse = (startGameResponseSuccess | startGameResponseError)

export const getStartGameUrl = () => {




  return `http://localhost:8085/game/start`
}

/**
 * 既存ユーザーをアーカイブし（未ログインユーザーは削除）、指定数の新規ユーザーを作成する。
 * 作成した全ユーザーのIDを返す（クライアント側でログインQR PDFを生成するために使用）。
 * @summary [管理者専用] 新規ゲームスタート
 */
export const startGame = async (gameStartRequest: GameStartRequest, options?: RequestInit): Promise<startGameResponse> => {

  const res = await fetch(getStartGameUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(gameStartRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: startGameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startGameResponse
}




export const getStartGameMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: GameStartRequest }) => {
    return startGame(arg, options);
  }
}
export const getStartGameMutationKey = () => [`http://localhost:8085/game/start`] as const;

export type StartGameMutationResult = NonNullable<Awaited<ReturnType<typeof startGame>>>

/**
 * @summary [管理者専用] 新規ゲームスタート
 */
export const useStartGame = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof startGame>>, TError, Key, GameStartRequest, Awaited<ReturnType<typeof startGame>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getStartGameMutationKey();
  const swrFn = getStartGameMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type archiveGameResponse204 = {
  data: void
  status: 204
}

export type archiveGameResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type archiveGameResponseSuccess = (archiveGameResponse204) & {
  headers: Headers;
};
export type archiveGameResponseError = (archiveGameResponse401) & {
  headers: Headers;
};

export type archiveGameResponse = (archiveGameResponseSuccess | archiveGameResponseError)

export const getArchiveGameUrl = () => {




  return `http://localhost:8085/game/archive`
}

/**
 * 既存ユーザーをアーカイブする。未ログインユーザーのレコードは削除する。
 * @summary [管理者専用] 一括アーカイブ
 */
export const archiveGame = async ( options?: RequestInit): Promise<archiveGameResponse> => {

  const res = await fetch(getArchiveGameUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: archiveGameResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as archiveGameResponse
}




export const getArchiveGameMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return archiveGame(options);
  }
}
export const getArchiveGameMutationKey = () => [`http://localhost:8085/game/archive`] as const;

export type ArchiveGameMutationResult = NonNullable<Awaited<ReturnType<typeof archiveGame>>>

/**
 * @summary [管理者専用] 一括アーカイブ
 */
export const useArchiveGame = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof archiveGame>>, TError, Key, Arguments, Awaited<ReturnType<typeof archiveGame>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getArchiveGameMutationKey();
  const swrFn = getArchiveGameMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
