/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
export type PhysicsType = typeof PhysicsType[keyof typeof PhysicsType];


export const PhysicsType = {
  slash: 'slash',
  blow: 'blow',
  shoot: 'shoot',
} as const;

export type ElementType = typeof ElementType[keyof typeof ElementType];


export const ElementType = {
  neutral: 'neutral',
  flame: 'flame',
  water: 'water',
  wood: 'wood',
  shine: 'shine',
  dark: 'dark',
} as const;

export type EffectType = typeof EffectType[keyof typeof EffectType];


export const EffectType = {
  heal: 'heal',
  buff: 'buff',
  debuff: 'debuff',
} as const;

export interface ErrorResponse {
  errors: string[];
}

export interface ImageResponse {
  id: number;
  url: string;
}

export interface UserLoginRequest {
  id: string;
}

export interface AdminLoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  authToken: string;
}

export interface WeaponResponse {
  id: number;
  name: string;
  physicsAttack: number;
  /** @nullable */
  elementAttack: number | null;
  physicsType: PhysicsType;
  elementType: ElementType;
}

export interface MeResponse {
  id: string;
  name: string;
  /** @nullable */
  avatarImageUrl?: string | null;
  level: number;
  hitPoint: number;
  experiencePoint: number;
  weapon?: WeaponResponse | null;
}

export interface UpdateMeRequest {
  name?: string;
  level?: number;
  hitPoint?: number;
  experiencePoint?: number;
  equippedWeaponId?: number;
  avatarImageId?: number;
}

export interface ItemResponse {
  id: number;
  name: string;
  effectType: EffectType;
  /** heal のみ */
  amount?: number;
  /** buff / debuff のみ */
  rate?: number;
  /** buff / debuff のみ */
  target?: string;
}

export type UserItemResponse = ItemResponse & {
  count: number;
};

export interface MonsterCatalogResponse {
  id: string;
}

export interface MonsterDetailResponse {
  id: string;
  name: string;
  attack: number;
  hitPoint: number;
  experiencePoint: number;
  slash?: number;
  blow?: number;
  shoot?: number;
  neutral?: number;
  flame?: number;
  water?: number;
  wood?: number;
  shine?: number;
  dark?: number;
  weapon?: WeaponResponse | null;
  item?: ItemResponse | null;
}

export interface UseItemRequest {
  itemId: number;
}

export interface ChangeWeaponRequest {
  weaponId: number;
}

export interface BossFinishResponse {
  /** クリアタイム（ミリ秒）。サーバーが battles.updated_at - battles.created_at で計算 */
  clearTime: number;
  experiencePoint: number;
  level: number;
  hitPoint: number;
}

export interface GameStartRequest {
  /**
     * 作成する新規ユーザー数
     * @minimum 1
     */
  count: number;
}

export interface BattleStartRequest {
  /** AES暗号化されたモンスタートークン */
  monsterToken: string;
}

export interface BattleStartResponse {
  token: string;
  seed: number;
}

export type BattleActionType = typeof BattleActionType[keyof typeof BattleActionType];


export const BattleActionType = {
  attack: 'attack',
  'use-item': 'use-item',
  'change-weapon': 'change-weapon',
} as const;

export interface BattleAction {
  turn: number;
  type: BattleActionType;
  /** use-item のとき必須 */
  itemId?: number;
  /** change-weapon のとき必須 */
  weaponId?: number;
}

export interface BattleFinishRequest {
  token: string;
  actions: BattleAction[];
}

export type BattleRewardResponseDrop = ({
  type: 'weapon' | 'item';
  /** @nullable */
  weaponId?: number | null;
  /** @nullable */
  itemId?: number | null;
}) | null;

export interface BattleRewardResponse {
  experiencePoint: number;
  level: number;
  hitPoint: number;
  drop?: BattleRewardResponseDrop;
}

export interface UserStoreRequest {
  name: string;
}

export interface UserStoreResponse {
  id: string;
}

/**
 * 認証エラー
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * リクエストエラー
 */
export type BadRequestResponse = ErrorResponse;

/**
 * リソースが見つからない
 */
export type NotFoundResponse = ErrorResponse;

export type OffsetParameter = number;

export type LimitParameter = number;

export type HealthCheck200 = {
  status: string;
};

export type UploadImageBody = {
  imageFile: Blob;
  directory: string;
};

export type UploadImage200 = {
  image: ImageResponse;
};

export type GetMe200 = {
  user: MeResponse;
};

export type GetItems200 = {
  items: UserItemResponse[];
};

export type GetWeapons200 = {
  weapons: WeaponResponse[];
};

export type GetMonstersParams = {
/**
 * @minimum 0
 */
offset?: OffsetParameter;
/**
 * @minimum 1
 */
limit?: LimitParameter;
};

export type GetMonsters200 = {
  monsters: (MonsterCatalogResponse | null)[];
  total: number;
};

export type GetMeWeaponIndexParams = {
/**
 * @minimum 0
 */
offset?: OffsetParameter;
/**
 * @minimum 1
 */
limit?: LimitParameter;
};

export type GetMeWeaponIndex200 = {
  weapons: (WeaponResponse | null)[];
  total: number;
};

export type GetMeItemIndexParams = {
/**
 * @minimum 0
 */
offset?: OffsetParameter;
/**
 * @minimum 1
 */
limit?: LimitParameter;
};

export type GetMeItemIndex200 = {
  items: (ItemResponse | null)[];
  total: number;
};

export type GetMonsterBattleTokens200 = {
  tokens: string[];
};

export type StartGame200 = {
  userIds: string[];
};

export type GetMonster200 = {
  monster: MonsterDetailResponse;
};

