// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
)

const findAdminByEmail = `-- name: FindAdminByEmail :one
SELECT id, email, password, remember_token, created_at, updated_at
FROM admins
WHERE email = ?
LIMIT 1
`

func (q *Queries) FindAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, findAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RememberToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
