// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createBattle = `-- name: CreateBattle :exec
INSERT INTO battles (id, user_id, monster_id, start_weapon_id, seed, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateBattleParams struct {
	ID            string         `db:"id" json:"id"`
	UserID        string         `db:"user_id" json:"user_id"`
	MonsterID     sql.NullString `db:"monster_id" json:"monster_id"`
	StartWeaponID sql.NullInt64  `db:"start_weapon_id" json:"start_weapon_id"`
	Seed          int64          `db:"seed" json:"seed"`
	Status        string         `db:"status" json:"status"`
}

func (q *Queries) CreateBattle(ctx context.Context, arg CreateBattleParams) error {
	_, err := q.db.ExecContext(ctx, createBattle,
		arg.ID,
		arg.UserID,
		arg.MonsterID,
		arg.StartWeaponID,
		arg.Seed,
		arg.Status,
	)
	return err
}

const getBattleByID = `-- name: GetBattleByID :one
SELECT id, user_id, monster_id, seed, status, created_at, updated_at, start_weapon_id FROM battles WHERE id = ? LIMIT 1
`

func (q *Queries) GetBattleByID(ctx context.Context, id string) (Battle, error) {
	row := q.db.QueryRowContext(ctx, getBattleByID, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MonsterID,
		&i.Seed,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartWeaponID,
	)
	return i, err
}

const updateBattleStatus = `-- name: UpdateBattleStatus :exec
UPDATE battles SET status = ?, updated_at = NOW() WHERE id = ?
`

type UpdateBattleStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) UpdateBattleStatus(ctx context.Context, arg UpdateBattleStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBattleStatus, arg.Status, arg.ID)
	return err
}

const upsertBossRecord = `-- name: UpsertBossRecord :exec
INSERT INTO boss_records (user_id, clear_time, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    clear_time = IF(VALUES(clear_time) < clear_time, VALUES(clear_time), clear_time),
    updated_at = NOW()
`

type UpsertBossRecordParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	ClearTime int32  `db:"clear_time" json:"clear_time"`
}

func (q *Queries) UpsertBossRecord(ctx context.Context, arg UpsertBossRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertBossRecord, arg.UserID, arg.ClearTime)
	return err
}
