// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image.sql

package dbgen

import (
	"context"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (directory, url, created_at)
VALUES (?, ?, NOW())
`

type CreateImageParams struct {
	Directory string `db:"directory" json:"directory"`
	Url       string `db:"url" json:"url"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage, arg.Directory, arg.Url)
	return err
}

const getLastInsertImage = `-- name: GetLastInsertImage :one
SELECT id, directory, url, created_at FROM images WHERE id = LAST_INSERT_ID() LIMIT 1
`

func (q *Queries) GetLastInsertImage(ctx context.Context) (Image, error) {
	row := q.db.QueryRowContext(ctx, getLastInsertImage)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Directory,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}
