// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countItemIndexByUserID = `-- name: CountItemIndexByUserID :one
SELECT COUNT(*) FROM item_entries WHERE user_id = ?
`

func (q *Queries) CountItemIndexByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemIndexByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decrementUserItem = `-- name: DecrementUserItem :exec
UPDATE user_items SET count = count - 1, updated_at = NOW()
WHERE user_id = ? AND item_id = ? AND count > 0
`

type DecrementUserItemParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ItemID int64  `db:"item_id" json:"item_id"`
}

func (q *Queries) DecrementUserItem(ctx context.Context, arg DecrementUserItemParams) error {
	_, err := q.db.ExecContext(ctx, decrementUserItem, arg.UserID, arg.ItemID)
	return err
}

const deleteUserItemIfZero = `-- name: DeleteUserItemIfZero :exec
DELETE FROM user_items WHERE user_id = ? AND item_id = ? AND count = 0
`

type DeleteUserItemIfZeroParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ItemID int64  `db:"item_id" json:"item_id"`
}

func (q *Queries) DeleteUserItemIfZero(ctx context.Context, arg DeleteUserItemIfZeroParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserItemIfZero, arg.UserID, arg.ItemID)
	return err
}

const getAllItemIDs = `-- name: GetAllItemIDs :many
SELECT id FROM items ORDER BY id
`

func (q *Queries) GetAllItemIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT i.id, i.name, i.index_number, i.effect_type, i.created_at, i.updated_at,
    hi.amount, bi.rate as buff_rate, bi.target as buff_target, di.rate as debuff_rate, di.target as debuff_target
FROM items i
LEFT JOIN heal_items hi ON i.id = hi.item_id
LEFT JOIN buff_items bi ON i.id = bi.item_id
LEFT JOIN debuff_items di ON i.id = di.item_id
WHERE i.id = ? LIMIT 1
`

type GetItemByIDRow struct {
	ID           int64          `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	IndexNumber  string         `db:"index_number" json:"index_number"`
	EffectType   string         `db:"effect_type" json:"effect_type"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	Amount       sql.NullInt32  `db:"amount" json:"amount"`
	BuffRate     sql.NullString `db:"buff_rate" json:"buff_rate"`
	BuffTarget   sql.NullString `db:"buff_target" json:"buff_target"`
	DebuffRate   sql.NullString `db:"debuff_rate" json:"debuff_rate"`
	DebuffTarget sql.NullString `db:"debuff_target" json:"debuff_target"`
}

func (q *Queries) GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IndexNumber,
		&i.EffectType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
		&i.BuffRate,
		&i.BuffTarget,
		&i.DebuffRate,
		&i.DebuffTarget,
	)
	return i, err
}

const getItemIndexByUserID = `-- name: GetItemIndexByUserID :many
SELECT i.id, i.name, i.index_number, i.effect_type, i.created_at, i.updated_at,
    hi.amount, bi.rate as buff_rate, bi.target as buff_target, di.rate as debuff_rate, di.target as debuff_target
FROM items i
INNER JOIN item_entries ie ON i.id = ie.item_id
LEFT JOIN heal_items hi ON i.id = hi.item_id
LEFT JOIN buff_items bi ON i.id = bi.item_id
LEFT JOIN debuff_items di ON i.id = di.item_id
WHERE ie.user_id = ?
ORDER BY i.id
LIMIT ? OFFSET ?
`

type GetItemIndexByUserIDParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type GetItemIndexByUserIDRow struct {
	ID           int64          `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	IndexNumber  string         `db:"index_number" json:"index_number"`
	EffectType   string         `db:"effect_type" json:"effect_type"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	Amount       sql.NullInt32  `db:"amount" json:"amount"`
	BuffRate     sql.NullString `db:"buff_rate" json:"buff_rate"`
	BuffTarget   sql.NullString `db:"buff_target" json:"buff_target"`
	DebuffRate   sql.NullString `db:"debuff_rate" json:"debuff_rate"`
	DebuffTarget sql.NullString `db:"debuff_target" json:"debuff_target"`
}

func (q *Queries) GetItemIndexByUserID(ctx context.Context, arg GetItemIndexByUserIDParams) ([]GetItemIndexByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemIndexByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemIndexByUserIDRow
	for rows.Next() {
		var i GetItemIndexByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IndexNumber,
			&i.EffectType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amount,
			&i.BuffRate,
			&i.BuffTarget,
			&i.DebuffRate,
			&i.DebuffTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByUserID = `-- name: GetItemsByUserID :many
SELECT i.id, i.name, i.index_number, i.effect_type, i.created_at, i.updated_at,
    hi.amount, bi.rate as buff_rate, bi.target as buff_target, di.rate as debuff_rate, di.target as debuff_target, ui.count
FROM items i
INNER JOIN user_items ui ON i.id = ui.item_id
LEFT JOIN heal_items hi ON i.id = hi.item_id
LEFT JOIN buff_items bi ON i.id = bi.item_id
LEFT JOIN debuff_items di ON i.id = di.item_id
WHERE ui.user_id = ?
`

type GetItemsByUserIDRow struct {
	ID           int64          `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	IndexNumber  string         `db:"index_number" json:"index_number"`
	EffectType   string         `db:"effect_type" json:"effect_type"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	Amount       sql.NullInt32  `db:"amount" json:"amount"`
	BuffRate     sql.NullString `db:"buff_rate" json:"buff_rate"`
	BuffTarget   sql.NullString `db:"buff_target" json:"buff_target"`
	DebuffRate   sql.NullString `db:"debuff_rate" json:"debuff_rate"`
	DebuffTarget sql.NullString `db:"debuff_target" json:"debuff_target"`
	Count        int32          `db:"count" json:"count"`
}

func (q *Queries) GetItemsByUserID(ctx context.Context, userID string) ([]GetItemsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByUserIDRow
	for rows.Next() {
		var i GetItemsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IndexNumber,
			&i.EffectType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amount,
			&i.BuffRate,
			&i.BuffTarget,
			&i.DebuffRate,
			&i.DebuffTarget,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantItemToEntry = `-- name: GrantItemToEntry :exec
INSERT IGNORE INTO item_entries (user_id, item_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type GrantItemToEntryParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ItemID int64  `db:"item_id" json:"item_id"`
}

func (q *Queries) GrantItemToEntry(ctx context.Context, arg GrantItemToEntryParams) error {
	_, err := q.db.ExecContext(ctx, grantItemToEntry, arg.UserID, arg.ItemID)
	return err
}

const grantItemToUser = `-- name: GrantItemToUser :exec
INSERT INTO user_items (user_id, item_id, count, created_at, updated_at)
VALUES (?, ?, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE count = count + 1, updated_at = NOW()
`

type GrantItemToUserParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ItemID int64  `db:"item_id" json:"item_id"`
}

func (q *Queries) GrantItemToUser(ctx context.Context, arg GrantItemToUserParams) error {
	_, err := q.db.ExecContext(ctx, grantItemToUser, arg.UserID, arg.ItemID)
	return err
}
