// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID            int64          `db:"id" json:"id"`
	Email         string         `db:"email" json:"email"`
	Password      string         `db:"password" json:"password"`
	RememberToken sql.NullString `db:"remember_token" json:"remember_token"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
}

type Battle struct {
	ID        string         `db:"id" json:"id"`
	UserID    string         `db:"user_id" json:"user_id"`
	MonsterID sql.NullString `db:"monster_id" json:"monster_id"`
	Seed      int64          `db:"seed" json:"seed"`
	// in_progress|completed|lost|expired
	Status        string        `db:"status" json:"status"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time     `db:"updated_at" json:"updated_at"`
	StartWeaponID sql.NullInt64 `db:"start_weapon_id" json:"start_weapon_id"`
}

type BossRecord struct {
	UserID string `db:"user_id" json:"user_id"`
	// milliseconds
	ClearTime int32     `db:"clear_time" json:"clear_time"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type BuffItem struct {
	ItemID    int64     `db:"item_id" json:"item_id"`
	Rate      string    `db:"rate" json:"rate"`
	Target    string    `db:"target" json:"target"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type DebuffItem struct {
	ItemID    int64     `db:"item_id" json:"item_id"`
	Rate      string    `db:"rate" json:"rate"`
	Target    string    `db:"target" json:"target"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type HealItem struct {
	ItemID    int64     `db:"item_id" json:"item_id"`
	Amount    int32     `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Image struct {
	ID        int64     `db:"id" json:"id"`
	Directory string    `db:"directory" json:"directory"`
	Url       string    `db:"url" json:"url"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Item struct {
	ID          int64     `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	IndexNumber string    `db:"index_number" json:"index_number"`
	EffectType  string    `db:"effect_type" json:"effect_type"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type ItemEntry struct {
	UserID    string    `db:"user_id" json:"user_id"`
	ItemID    int64     `db:"item_id" json:"item_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Monster struct {
	ID               string        `db:"id" json:"id"`
	WeaponID         sql.NullInt64 `db:"weapon_id" json:"weapon_id"`
	ItemID           sql.NullInt64 `db:"item_id" json:"item_id"`
	IndexNumber      string        `db:"index_number" json:"index_number"`
	Name             string        `db:"name" json:"name"`
	Attack           int32         `db:"attack" json:"attack"`
	HitPoint         int32         `db:"hit_point" json:"hit_point"`
	ExperiencePoint  int32         `db:"experience_point" json:"experience_point"`
	Slash            string        `db:"slash" json:"slash"`
	Blow             string        `db:"blow" json:"blow"`
	Shoot            string        `db:"shoot" json:"shoot"`
	Neutral          string        `db:"neutral" json:"neutral"`
	Flame            string        `db:"flame" json:"flame"`
	Water            string        `db:"water" json:"water"`
	Wood             string        `db:"wood" json:"wood"`
	Shine            string        `db:"shine" json:"shine"`
	Dark             string        `db:"dark" json:"dark"`
	CreatedAt        time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time     `db:"updated_at" json:"updated_at"`
	RecommendedLevel int32         `db:"recommended_level" json:"recommended_level"`
}

type MonsterEntry struct {
	UserID    string    `db:"user_id" json:"user_id"`
	MonsterID string    `db:"monster_id" json:"monster_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID               string         `db:"id" json:"id"`
	EquippedWeaponID sql.NullInt64  `db:"equipped_weapon_id" json:"equipped_weapon_id"`
	AvatarImageID    sql.NullInt64  `db:"avatar_image_id" json:"avatar_image_id"`
	Name             string         `db:"name" json:"name"`
	Level            int32          `db:"level" json:"level"`
	HitPoint         int32          `db:"hit_point" json:"hit_point"`
	ExperiencePoint  int32          `db:"experience_point" json:"experience_point"`
	RememberToken    sql.NullString `db:"remember_token" json:"remember_token"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	IsArchived       bool           `db:"is_archived" json:"is_archived"`
	IsActivated      bool           `db:"is_activated" json:"is_activated"`
}

type UserItem struct {
	UserID    string    `db:"user_id" json:"user_id"`
	ItemID    int64     `db:"item_id" json:"item_id"`
	Count     int32     `db:"count" json:"count"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type UserWeapon struct {
	UserID    string    `db:"user_id" json:"user_id"`
	WeaponID  int64     `db:"weapon_id" json:"weapon_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Weapon struct {
	ID            int64         `db:"id" json:"id"`
	Name          string        `db:"name" json:"name"`
	IndexNumber   string        `db:"index_number" json:"index_number"`
	PhysicsAttack int32         `db:"physics_attack" json:"physics_attack"`
	ElementAttack sql.NullInt32 `db:"element_attack" json:"element_attack"`
	PhysicsType   string        `db:"physics_type" json:"physics_type"`
	ElementType   string        `db:"element_type" json:"element_type"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time     `db:"updated_at" json:"updated_at"`
}

type WeaponEntry struct {
	UserID    string    `db:"user_id" json:"user_id"`
	WeaponID  int64     `db:"weapon_id" json:"weapon_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
