// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monster.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countMonsterCatalogByUserID = `-- name: CountMonsterCatalogByUserID :one
SELECT COUNT(*) FROM monster_entries WHERE user_id = ?
`

func (q *Queries) CountMonsterCatalogByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonsterCatalogByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllMonsterIDs = `-- name: GetAllMonsterIDs :many
SELECT id FROM monsters ORDER BY index_number
`

func (q *Queries) GetAllMonsterIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllMonsterIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonsterByID = `-- name: GetMonsterByID :one
SELECT m.id, m.weapon_id, m.item_id, m.index_number, m.name, m.attack, m.hit_point, m.experience_point,
    m.recommended_level, m.slash, m.blow, m.shoot, m.neutral, m.flame, m.water, m.wood, m.shine, m.dark,
    m.created_at, m.updated_at,
    w.id as weapon_id_j, w.name as weapon_name, w.index_number as weapon_index_number,
    w.physics_attack, w.element_attack, w.physics_type, w.element_type,
    w.created_at as weapon_created_at, w.updated_at as weapon_updated_at,
    i.id as item_id_j, i.name as item_name, i.index_number as item_index_number, i.effect_type,
    i.created_at as item_created_at, i.updated_at as item_updated_at,
    hi.amount, bi.rate as buff_rate, bi.target as buff_target, di.rate as debuff_rate, di.target as debuff_target
FROM monsters m
LEFT JOIN weapons w ON m.weapon_id = w.id
LEFT JOIN items i ON m.item_id = i.id
LEFT JOIN heal_items hi ON i.id = hi.item_id
LEFT JOIN buff_items bi ON i.id = bi.item_id
LEFT JOIN debuff_items di ON i.id = di.item_id
WHERE m.id = ? LIMIT 1
`

type GetMonsterByIDRow struct {
	ID                string         `db:"id" json:"id"`
	WeaponID          sql.NullInt64  `db:"weapon_id" json:"weapon_id"`
	ItemID            sql.NullInt64  `db:"item_id" json:"item_id"`
	IndexNumber       string         `db:"index_number" json:"index_number"`
	Name              string         `db:"name" json:"name"`
	Attack            int32          `db:"attack" json:"attack"`
	HitPoint          int32          `db:"hit_point" json:"hit_point"`
	ExperiencePoint   int32          `db:"experience_point" json:"experience_point"`
	RecommendedLevel  int32          `db:"recommended_level" json:"recommended_level"`
	Slash             string         `db:"slash" json:"slash"`
	Blow              string         `db:"blow" json:"blow"`
	Shoot             string         `db:"shoot" json:"shoot"`
	Neutral           string         `db:"neutral" json:"neutral"`
	Flame             string         `db:"flame" json:"flame"`
	Water             string         `db:"water" json:"water"`
	Wood              string         `db:"wood" json:"wood"`
	Shine             string         `db:"shine" json:"shine"`
	Dark              string         `db:"dark" json:"dark"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	WeaponIDJ         sql.NullInt64  `db:"weapon_id_j" json:"weapon_id_j"`
	WeaponName        sql.NullString `db:"weapon_name" json:"weapon_name"`
	WeaponIndexNumber sql.NullString `db:"weapon_index_number" json:"weapon_index_number"`
	PhysicsAttack     sql.NullInt32  `db:"physics_attack" json:"physics_attack"`
	ElementAttack     sql.NullInt32  `db:"element_attack" json:"element_attack"`
	PhysicsType       sql.NullString `db:"physics_type" json:"physics_type"`
	ElementType       sql.NullString `db:"element_type" json:"element_type"`
	WeaponCreatedAt   sql.NullTime   `db:"weapon_created_at" json:"weapon_created_at"`
	WeaponUpdatedAt   sql.NullTime   `db:"weapon_updated_at" json:"weapon_updated_at"`
	ItemIDJ           sql.NullInt64  `db:"item_id_j" json:"item_id_j"`
	ItemName          sql.NullString `db:"item_name" json:"item_name"`
	ItemIndexNumber   sql.NullString `db:"item_index_number" json:"item_index_number"`
	EffectType        sql.NullString `db:"effect_type" json:"effect_type"`
	ItemCreatedAt     sql.NullTime   `db:"item_created_at" json:"item_created_at"`
	ItemUpdatedAt     sql.NullTime   `db:"item_updated_at" json:"item_updated_at"`
	Amount            sql.NullInt32  `db:"amount" json:"amount"`
	BuffRate          sql.NullString `db:"buff_rate" json:"buff_rate"`
	BuffTarget        sql.NullString `db:"buff_target" json:"buff_target"`
	DebuffRate        sql.NullString `db:"debuff_rate" json:"debuff_rate"`
	DebuffTarget      sql.NullString `db:"debuff_target" json:"debuff_target"`
}

func (q *Queries) GetMonsterByID(ctx context.Context, id string) (GetMonsterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMonsterByID, id)
	var i GetMonsterByIDRow
	err := row.Scan(
		&i.ID,
		&i.WeaponID,
		&i.ItemID,
		&i.IndexNumber,
		&i.Name,
		&i.Attack,
		&i.HitPoint,
		&i.ExperiencePoint,
		&i.RecommendedLevel,
		&i.Slash,
		&i.Blow,
		&i.Shoot,
		&i.Neutral,
		&i.Flame,
		&i.Water,
		&i.Wood,
		&i.Shine,
		&i.Dark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeaponIDJ,
		&i.WeaponName,
		&i.WeaponIndexNumber,
		&i.PhysicsAttack,
		&i.ElementAttack,
		&i.PhysicsType,
		&i.ElementType,
		&i.WeaponCreatedAt,
		&i.WeaponUpdatedAt,
		&i.ItemIDJ,
		&i.ItemName,
		&i.ItemIndexNumber,
		&i.EffectType,
		&i.ItemCreatedAt,
		&i.ItemUpdatedAt,
		&i.Amount,
		&i.BuffRate,
		&i.BuffTarget,
		&i.DebuffRate,
		&i.DebuffTarget,
	)
	return i, err
}

const getMonsterCatalogByUserID = `-- name: GetMonsterCatalogByUserID :many
SELECT me.monster_id FROM monster_entries me
WHERE me.user_id = ?
ORDER BY me.created_at
LIMIT ? OFFSET ?
`

type GetMonsterCatalogByUserIDParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetMonsterCatalogByUserID(ctx context.Context, arg GetMonsterCatalogByUserIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMonsterCatalogByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var monster_id string
		if err := rows.Scan(&monster_id); err != nil {
			return nil, err
		}
		items = append(items, monster_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMonsterEntryRegistered = `-- name: IsMonsterEntryRegistered :one
SELECT COUNT(*) FROM monster_entries WHERE user_id = ? AND monster_id = ?
`

type IsMonsterEntryRegisteredParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	MonsterID string `db:"monster_id" json:"monster_id"`
}

func (q *Queries) IsMonsterEntryRegistered(ctx context.Context, arg IsMonsterEntryRegisteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isMonsterEntryRegistered, arg.UserID, arg.MonsterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registerMonsterEntry = `-- name: RegisterMonsterEntry :exec
INSERT IGNORE INTO monster_entries (user_id, monster_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type RegisterMonsterEntryParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	MonsterID string `db:"monster_id" json:"monster_id"`
}

func (q *Queries) RegisterMonsterEntry(ctx context.Context, arg RegisterMonsterEntryParams) error {
	_, err := q.db.ExecContext(ctx, registerMonsterEntry, arg.UserID, arg.MonsterID)
	return err
}
