// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CountItemIndexByUserID(ctx context.Context, userID string) (int64, error)
	CountMonsterCatalogByUserID(ctx context.Context, userID string) (int64, error)
	CountWeaponIndexByUserID(ctx context.Context, userID string) (int64, error)
	CreateBattle(ctx context.Context, arg CreateBattleParams) error
	CreateImage(ctx context.Context, arg CreateImageParams) error
	DecrementUserItem(ctx context.Context, arg DecrementUserItemParams) error
	DeleteUserItemIfZero(ctx context.Context, arg DeleteUserItemIfZeroParams) error
	FindAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetBattleByID(ctx context.Context, id string) (Battle, error)
	GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error)
	GetItemIndexByUserID(ctx context.Context, arg GetItemIndexByUserIDParams) ([]GetItemIndexByUserIDRow, error)
	GetItemsByUserID(ctx context.Context, userID string) ([]GetItemsByUserIDRow, error)
	GetLastInsertImage(ctx context.Context) (Image, error)
	GetMonsterByID(ctx context.Context, id string) (GetMonsterByIDRow, error)
	GetMonsterCatalogByUserID(ctx context.Context, arg GetMonsterCatalogByUserIDParams) ([]string, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetWeaponByID(ctx context.Context, id int64) (Weapon, error)
	GetWeaponIndexByUserID(ctx context.Context, arg GetWeaponIndexByUserIDParams) ([]Weapon, error)
	GetWeaponsByUserID(ctx context.Context, userID string) ([]Weapon, error)
	GrantItemToEntry(ctx context.Context, arg GrantItemToEntryParams) error
	GrantItemToUser(ctx context.Context, arg GrantItemToUserParams) error
	GrantWeaponToEntry(ctx context.Context, arg GrantWeaponToEntryParams) error
	GrantWeaponToUser(ctx context.Context, arg GrantWeaponToUserParams) error
	IsMonsterEntryRegistered(ctx context.Context, arg IsMonsterEntryRegisteredParams) (int64, error)
	IsWeaponOwnedByUser(ctx context.Context, arg IsWeaponOwnedByUserParams) (int64, error)
	RegisterMonsterEntry(ctx context.Context, arg RegisterMonsterEntryParams) error
	UpdateBattleStatus(ctx context.Context, arg UpdateBattleStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertBossRecord(ctx context.Context, arg UpsertBossRecordParams) error
}

var _ Querier = (*Queries)(nil)
