// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	ActivateUser(ctx context.Context, id string) error
	ArchiveAllUsers(ctx context.Context) error
	CountItemIndexByUserID(ctx context.Context, userID string) (int64, error)
	CountMonsterCatalogByUserID(ctx context.Context, userID string) (int64, error)
	CountWeaponIndexByUserID(ctx context.Context, userID string) (int64, error)
	CreateBattle(ctx context.Context, arg CreateBattleParams) error
	CreateImage(ctx context.Context, arg CreateImageParams) error
	CreateUser(ctx context.Context, id string) error
	DecrementUserItem(ctx context.Context, arg DecrementUserItemParams) error
	DeleteInactiveUsers(ctx context.Context) error
	DeleteUserItemIfZero(ctx context.Context, arg DeleteUserItemIfZeroParams) error
	FindAdminByEmail(ctx context.Context, email string) (Admin, error)
	// 図鑑番号は 4 桁ゼロ埋めの数字なので、文字列順でそのまま番号順になる。
	GetAllItemIDs(ctx context.Context) ([]int64, error)
	GetAllMonsterIDs(ctx context.Context) ([]string, error)
	GetAllUserIDs(ctx context.Context) ([]string, error)
	// 図鑑番号は 4 桁ゼロ埋めの数字なので、文字列順でそのまま番号順になる。
	GetAllWeaponIDs(ctx context.Context) ([]int64, error)
	GetBattleByID(ctx context.Context, id string) (Battle, error)
	GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error)
	GetItemIndexByUserID(ctx context.Context, arg GetItemIndexByUserIDParams) ([]GetItemIndexByUserIDRow, error)
	GetItemsByUserID(ctx context.Context, userID string) ([]GetItemsByUserIDRow, error)
	GetLastInsertImage(ctx context.Context) (Image, error)
	GetMonsterByID(ctx context.Context, id string) (GetMonsterByIDRow, error)
	GetMonsterCatalogByUserID(ctx context.Context, arg GetMonsterCatalogByUserIDParams) ([]string, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetWeaponByID(ctx context.Context, id int64) (Weapon, error)
	GetWeaponIndexByUserID(ctx context.Context, arg GetWeaponIndexByUserIDParams) ([]Weapon, error)
	GetWeaponsByUserID(ctx context.Context, userID string) ([]Weapon, error)
	GrantItemToEntry(ctx context.Context, arg GrantItemToEntryParams) error
	GrantItemToUser(ctx context.Context, arg GrantItemToUserParams) error
	GrantWeaponToEntry(ctx context.Context, arg GrantWeaponToEntryParams) error
	GrantWeaponToUser(ctx context.Context, arg GrantWeaponToUserParams) error
	IsMonsterEntryRegistered(ctx context.Context, arg IsMonsterEntryRegisteredParams) (int64, error)
	IsWeaponOwnedByUser(ctx context.Context, arg IsWeaponOwnedByUserParams) (int64, error)
	RegisterMonsterEntry(ctx context.Context, arg RegisterMonsterEntryParams) error
	UpdateBattleStatus(ctx context.Context, arg UpdateBattleStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertBossRecord(ctx context.Context, arg UpsertBossRecordParams) error
}

var _ Querier = (*Queries)(nil)
