// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weapon.sql

package dbgen

import (
	"context"
)

const countWeaponIndexByUserID = `-- name: CountWeaponIndexByUserID :one
SELECT COUNT(*) FROM weapon_entries WHERE user_id = ?
`

func (q *Queries) CountWeaponIndexByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeaponIndexByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllWeaponSummaries = `-- name: GetAllWeaponSummaries :many
SELECT id, name, index_number FROM weapons ORDER BY index_number
`

type GetAllWeaponSummariesRow struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	IndexNumber string `db:"index_number" json:"index_number"`
}

// 管理画面の一覧用。図鑑番号は 4 桁ゼロ埋めなので文字列順がそのまま番号順。
func (q *Queries) GetAllWeaponSummaries(ctx context.Context) ([]GetAllWeaponSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWeaponSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWeaponSummariesRow
	for rows.Next() {
		var i GetAllWeaponSummariesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IndexNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponByID = `-- name: GetWeaponByID :one
SELECT id, name, index_number, physics_attack, element_attack, physics_type, element_type, created_at, updated_at FROM weapons WHERE id = ? LIMIT 1
`

func (q *Queries) GetWeaponByID(ctx context.Context, id int64) (Weapon, error) {
	row := q.db.QueryRowContext(ctx, getWeaponByID, id)
	var i Weapon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IndexNumber,
		&i.PhysicsAttack,
		&i.ElementAttack,
		&i.PhysicsType,
		&i.ElementType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeaponIndexByUserID = `-- name: GetWeaponIndexByUserID :many
SELECT w.id, w.name, w.index_number, w.physics_attack, w.element_attack, w.physics_type, w.element_type, w.created_at, w.updated_at FROM weapons w
INNER JOIN weapon_entries we ON w.id = we.weapon_id
WHERE we.user_id = ?
ORDER BY w.id
LIMIT ? OFFSET ?
`

type GetWeaponIndexByUserIDParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetWeaponIndexByUserID(ctx context.Context, arg GetWeaponIndexByUserIDParams) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getWeaponIndexByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IndexNumber,
			&i.PhysicsAttack,
			&i.ElementAttack,
			&i.PhysicsType,
			&i.ElementType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeaponsByUserID = `-- name: GetWeaponsByUserID :many
SELECT w.id, w.name, w.index_number, w.physics_attack, w.element_attack, w.physics_type, w.element_type, w.created_at, w.updated_at FROM weapons w
INNER JOIN user_weapons uw ON w.id = uw.weapon_id
WHERE uw.user_id = ?
`

func (q *Queries) GetWeaponsByUserID(ctx context.Context, userID string) ([]Weapon, error) {
	rows, err := q.db.QueryContext(ctx, getWeaponsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weapon
	for rows.Next() {
		var i Weapon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IndexNumber,
			&i.PhysicsAttack,
			&i.ElementAttack,
			&i.PhysicsType,
			&i.ElementType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantWeaponToEntry = `-- name: GrantWeaponToEntry :exec
INSERT IGNORE INTO weapon_entries (user_id, weapon_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type GrantWeaponToEntryParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	WeaponID int64  `db:"weapon_id" json:"weapon_id"`
}

func (q *Queries) GrantWeaponToEntry(ctx context.Context, arg GrantWeaponToEntryParams) error {
	_, err := q.db.ExecContext(ctx, grantWeaponToEntry, arg.UserID, arg.WeaponID)
	return err
}

const grantWeaponToUser = `-- name: GrantWeaponToUser :exec
INSERT IGNORE INTO user_weapons (user_id, weapon_id, created_at, updated_at)
VALUES (?, ?, NOW(), NOW())
`

type GrantWeaponToUserParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	WeaponID int64  `db:"weapon_id" json:"weapon_id"`
}

func (q *Queries) GrantWeaponToUser(ctx context.Context, arg GrantWeaponToUserParams) error {
	_, err := q.db.ExecContext(ctx, grantWeaponToUser, arg.UserID, arg.WeaponID)
	return err
}

const isWeaponOwnedByUser = `-- name: IsWeaponOwnedByUser :one
SELECT COUNT(*) FROM user_weapons WHERE user_id = ? AND weapon_id = ?
`

type IsWeaponOwnedByUserParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	WeaponID int64  `db:"weapon_id" json:"weapon_id"`
}

func (q *Queries) IsWeaponOwnedByUser(ctx context.Context, arg IsWeaponOwnedByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isWeaponOwnedByUser, arg.UserID, arg.WeaponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
