/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ErrorResponse,
  GetMonster200,
  GetMonsterBattleTokens200,
  GetMonsterSummaries200,
  GetMonsters200,
  GetMonstersParams,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getMonstersResponse200 = {
  data: GetMonsters200
  status: 200
}

export type getMonstersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonstersResponseSuccess = (getMonstersResponse200) & {
  headers: Headers;
};
export type getMonstersResponseError = (getMonstersResponse401) & {
  headers: Headers;
};

export type getMonstersResponse = (getMonstersResponseSuccess | getMonstersResponseError)

export const getGetMonstersUrl = (params?: GetMonstersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/monsters/index?${stringifiedParams}` : `http://localhost:8085/monsters/index`
}

/**
 * @summary モンスター図鑑取得
 */
export const getMonsters = async (params?: GetMonstersParams, options?: RequestInit): Promise<getMonstersResponse> => {

  const res = await fetch(getGetMonstersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonstersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonstersResponse
}




export const getGetMonstersKey = (params?: GetMonstersParams,) => [`http://localhost:8085/monsters/index`, ...(params ? [params]: [])] as const;

export type GetMonstersQueryResult = NonNullable<Awaited<ReturnType<typeof getMonsters>>>

/**
 * @summary モンスター図鑑取得
 */
export const useGetMonsters = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMonstersParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonsters>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonstersKey(params) : null);
  const swrFn = () => getMonsters(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMonsterSummariesResponse200 = {
  data: GetMonsterSummaries200
  status: 200
}

export type getMonsterSummariesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonsterSummariesResponseSuccess = (getMonsterSummariesResponse200) & {
  headers: Headers;
};
export type getMonsterSummariesResponseError = (getMonsterSummariesResponse401) & {
  headers: Headers;
};

export type getMonsterSummariesResponse = (getMonsterSummariesResponseSuccess | getMonsterSummariesResponseError)

export const getGetMonsterSummariesUrl = () => {




  return `http://localhost:8085/monsters/summaries`
}

/**
 * マスタに登録されている全モンスターを図鑑番号の昇順で返す。管理画面が
 * 「何が存在するか」を把握するために使う。どの画像を割り当てるかは
 * フロント側の関心なので、ここでは画像情報は一切返さない。
 * @summary [管理者専用] 全モンスターの一覧取得
 */
export const getMonsterSummaries = async ( options?: RequestInit): Promise<getMonsterSummariesResponse> => {

  const res = await fetch(getGetMonsterSummariesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonsterSummariesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonsterSummariesResponse
}




export const getGetMonsterSummariesKey = () => [`http://localhost:8085/monsters/summaries`] as const;

export type GetMonsterSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof getMonsterSummaries>>>

/**
 * @summary [管理者専用] 全モンスターの一覧取得
 */
export const useGetMonsterSummaries = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonsterSummaries>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonsterSummariesKey() : null);
  const swrFn = () => getMonsterSummaries(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMonsterBattleTokensResponse200 = {
  data: GetMonsterBattleTokens200
  status: 200
}

export type getMonsterBattleTokensResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonsterBattleTokensResponseSuccess = (getMonsterBattleTokensResponse200) & {
  headers: Headers;
};
export type getMonsterBattleTokensResponseError = (getMonsterBattleTokensResponse401) & {
  headers: Headers;
};

export type getMonsterBattleTokensResponse = (getMonsterBattleTokensResponseSuccess | getMonsterBattleTokensResponseError)

export const getGetMonsterBattleTokensUrl = () => {




  return `http://localhost:8085/monsters/battle-tokens`
}

/**
 * @summary [管理者専用] 全モンスターの暗号化バトルトークン一覧取得
 */
export const getMonsterBattleTokens = async ( options?: RequestInit): Promise<getMonsterBattleTokensResponse> => {

  const res = await fetch(getGetMonsterBattleTokensUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonsterBattleTokensResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonsterBattleTokensResponse
}




export const getGetMonsterBattleTokensKey = () => [`http://localhost:8085/monsters/battle-tokens`] as const;

export type GetMonsterBattleTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getMonsterBattleTokens>>>

/**
 * @summary [管理者専用] 全モンスターの暗号化バトルトークン一覧取得
 */
export const useGetMonsterBattleTokens = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonsterBattleTokens>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonsterBattleTokensKey() : null);
  const swrFn = () => getMonsterBattleTokens(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMonsterResponse200 = {
  data: GetMonster200
  status: 200
}

export type getMonsterResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonsterResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMonsterResponseSuccess = (getMonsterResponse200) & {
  headers: Headers;
};
export type getMonsterResponseError = (getMonsterResponse401 | getMonsterResponse404) & {
  headers: Headers;
};

export type getMonsterResponse = (getMonsterResponseSuccess | getMonsterResponseError)

export const getGetMonsterUrl = (monsterId: string,) => {




  return `http://localhost:8085/monsters/${monsterId}`
}

/**
 * @summary モンスター詳細取得
 */
export const getMonster = async (monsterId: string, options?: RequestInit): Promise<getMonsterResponse> => {

  const res = await fetch(getGetMonsterUrl(monsterId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonsterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonsterResponse
}




export const getGetMonsterKey = (monsterId: string,) => [`http://localhost:8085/monsters/${monsterId}`] as const;

export type GetMonsterQueryResult = NonNullable<Awaited<ReturnType<typeof getMonster>>>

/**
 * @summary モンスター詳細取得
 */
export const useGetMonster = <TError = Promise<UnauthorizedResponse | ErrorResponse>>(
  monsterId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonster>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && monsterId !== null && monsterId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonsterKey(monsterId) : null);
  const swrFn = () => getMonster(monsterId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
