/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  ErrorResponse,
  GetMonster200,
  GetMonsters200,
  GetMonstersParams,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getMonstersResponse200 = {
  data: GetMonsters200
  status: 200
}

export type getMonstersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonstersResponseSuccess = (getMonstersResponse200) & {
  headers: Headers;
};
export type getMonstersResponseError = (getMonstersResponse401) & {
  headers: Headers;
};

export type getMonstersResponse = (getMonstersResponseSuccess | getMonstersResponseError)

export const getGetMonstersUrl = (params?: GetMonstersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/monsters/index?${stringifiedParams}` : `http://localhost:8085/monsters/index`
}

/**
 * @summary モンスター図鑑取得
 */
export const getMonsters = async (params?: GetMonstersParams, options?: RequestInit): Promise<getMonstersResponse> => {

  const res = await fetch(getGetMonstersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonstersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonstersResponse
}




export const getGetMonstersKey = (params?: GetMonstersParams,) => [`http://localhost:8085/monsters/index`, ...(params ? [params]: [])] as const;

export type GetMonstersQueryResult = NonNullable<Awaited<ReturnType<typeof getMonsters>>>

/**
 * @summary モンスター図鑑取得
 */
export const useGetMonsters = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMonstersParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonsters>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonstersKey(params) : null);
  const swrFn = () => getMonsters(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMonsterResponse200 = {
  data: GetMonster200
  status: 200
}

export type getMonsterResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMonsterResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMonsterResponseSuccess = (getMonsterResponse200) & {
  headers: Headers;
};
export type getMonsterResponseError = (getMonsterResponse401 | getMonsterResponse404) & {
  headers: Headers;
};

export type getMonsterResponse = (getMonsterResponseSuccess | getMonsterResponseError)

export const getGetMonsterUrl = (monsterId: string,) => {




  return `http://localhost:8085/monsters/${monsterId}`
}

/**
 * @summary モンスター詳細取得
 */
export const getMonster = async (monsterId: string, options?: RequestInit): Promise<getMonsterResponse> => {

  const res = await fetch(getGetMonsterUrl(monsterId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMonsterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMonsterResponse
}




export const getGetMonsterKey = (monsterId: string,) => [`http://localhost:8085/monsters/${monsterId}`] as const;

export type GetMonsterQueryResult = NonNullable<Awaited<ReturnType<typeof getMonster>>>

/**
 * @summary モンスター詳細取得
 */
export const useGetMonster = <TError = Promise<UnauthorizedResponse | ErrorResponse>>(
  monsterId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMonster>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && monsterId !== null && monsterId !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMonsterKey(monsterId) : null);
  const swrFn = () => getMonster(monsterId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
