/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetMe200,
  UnauthorizedResponse,
  UpdateMeRequest
} from '../bunkasaiRPGAPI.schemas';






 export type getMeResponse200 = {
  data: GetMe200
  status: 200
}

export type getMeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401) & {
  headers: Headers;
};

export type getMeResponse = (getMeResponseSuccess | getMeResponseError)

export const getGetMeUrl = () => {




  return `http://localhost:8085/me`
}

/**
 * @summary ログインユーザー情報取得
 */
export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {

  const res = await fetch(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeResponse
}




export const getGetMeKey = () => [`http://localhost:8085/me`] as const;

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>

/**
 * @summary ログインユーザー情報取得
 */
export const useGetMe = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMe>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMeKey() : null);
  const swrFn = () => getMe(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type updateMeResponse204 = {
  data: void
  status: 204
}

export type updateMeResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateMeResponseSuccess = (updateMeResponse204) & {
  headers: Headers;
};
export type updateMeResponseError = (updateMeResponse401) & {
  headers: Headers;
};

export type updateMeResponse = (updateMeResponseSuccess | updateMeResponseError)

export const getUpdateMeUrl = () => {




  return `http://localhost:8085/me`
}

/**
 * @summary ログインユーザー情報更新
 */
export const updateMe = async (updateMeRequest: UpdateMeRequest, options?: RequestInit): Promise<updateMeResponse> => {

  const res = await fetch(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMeRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateMeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as updateMeResponse
}




export const getUpdateMeMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateMeRequest }) => {
    return updateMe(arg, options);
  }
}
export const getUpdateMeMutationKey = () => [`http://localhost:8085/me`] as const;

export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>

/**
 * @summary ログインユーザー情報更新
 */
export const useUpdateMe = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateMe>>, TError, Key, UpdateMeRequest, Awaited<ReturnType<typeof updateMe>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateMeMutationKey();
  const swrFn = getUpdateMeMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
