/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Arguments,
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BattleFinishRequest,
  BattleStartResponse,
  BossFinishResponse,
  ErrorResponse,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type startBossBattleResponse200 = {
  data: BattleStartResponse
  status: 200
}

export type startBossBattleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type startBossBattleResponseSuccess = (startBossBattleResponse200) & {
  headers: Headers;
};
export type startBossBattleResponseError = (startBossBattleResponse401) & {
  headers: Headers;
};

export type startBossBattleResponse = (startBossBattleResponseSuccess | startBossBattleResponseError)

export const getStartBossBattleUrl = () => {




  return `http://localhost:8085/boss-battles/start`
}

/**
 * @summary ボスバトル開始
 */
export const startBossBattle = async ( options?: RequestInit): Promise<startBossBattleResponse> => {

  const res = await fetch(getStartBossBattleUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: startBossBattleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as startBossBattleResponse
}




export const getStartBossBattleMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return startBossBattle(options);
  }
}
export const getStartBossBattleMutationKey = () => [`http://localhost:8085/boss-battles/start`] as const;

export type StartBossBattleMutationResult = NonNullable<Awaited<ReturnType<typeof startBossBattle>>>

/**
 * @summary ボスバトル開始
 */
export const useStartBossBattle = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof startBossBattle>>, TError, Key, Arguments, Awaited<ReturnType<typeof startBossBattle>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getStartBossBattleMutationKey();
  const swrFn = getStartBossBattleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type finishBossBattleResponse200 = {
  data: BossFinishResponse
  status: 200
}

export type finishBossBattleResponse400 = {
  data: ErrorResponse
  status: 400
}

export type finishBossBattleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type finishBossBattleResponseSuccess = (finishBossBattleResponse200) & {
  headers: Headers;
};
export type finishBossBattleResponseError = (finishBossBattleResponse400 | finishBossBattleResponse401) & {
  headers: Headers;
};

export type finishBossBattleResponse = (finishBossBattleResponseSuccess | finishBossBattleResponseError)

export const getFinishBossBattleUrl = () => {




  return `http://localhost:8085/boss-battles/finish`
}

/**
 * @summary ボスバトル終了（クリアタイムはサーバーが計測）
 */
export const finishBossBattle = async (battleFinishRequest: BattleFinishRequest, options?: RequestInit): Promise<finishBossBattleResponse> => {

  const res = await fetch(getFinishBossBattleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(battleFinishRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: finishBossBattleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as finishBossBattleResponse
}




export const getFinishBossBattleMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BattleFinishRequest }) => {
    return finishBossBattle(arg, options);
  }
}
export const getFinishBossBattleMutationKey = () => [`http://localhost:8085/boss-battles/finish`] as const;

export type FinishBossBattleMutationResult = NonNullable<Awaited<ReturnType<typeof finishBossBattle>>>

/**
 * @summary ボスバトル終了（クリアタイムはサーバーが計測）
 */
export const useFinishBossBattle = <TError = Promise<ErrorResponse | UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof finishBossBattle>>, TError, Key, BattleFinishRequest, Awaited<ReturnType<typeof finishBossBattle>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getFinishBossBattleMutationKey();
  const swrFn = getFinishBossBattleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
