/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ChangeWeaponRequest,
  ErrorResponse,
  UnauthorizedResponse,
  UseItemRequest
} from '../bunkasaiRPGAPI.schemas';






 export type useMeItemResponse204 = {
  data: void
  status: 204
}

export type useMeItemResponse400 = {
  data: ErrorResponse
  status: 400
}

export type useMeItemResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type useMeItemResponseSuccess = (useMeItemResponse204) & {
  headers: Headers;
};
export type useMeItemResponseError = (useMeItemResponse400 | useMeItemResponse401) & {
  headers: Headers;
};

export type useMeItemResponse = (useMeItemResponseSuccess | useMeItemResponseError)

export const getUseMeItemUrl = () => {




  return `http://localhost:8085/actions/use-items`
}

/**
 * @summary アイテム使用
 */
export const useMeItem = async (useItemRequest: UseItemRequest, options?: RequestInit): Promise<useMeItemResponse> => {

  const res = await fetch(getUseMeItemUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(useItemRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: useMeItemResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as useMeItemResponse
}




export const getUseMeItemMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UseItemRequest }) => {
    return useMeItem(arg, options);
  }
}
export const getUseMeItemMutationKey = () => [`http://localhost:8085/actions/use-items`] as const;

export type UseMeItemMutationResult = NonNullable<Awaited<ReturnType<typeof useMeItem>>>

/**
 * @summary アイテム使用
 */
export const useUseMeItem = <TError = Promise<ErrorResponse | UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof useMeItem>>, TError, Key, UseItemRequest, Awaited<ReturnType<typeof useMeItem>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUseMeItemMutationKey();
  const swrFn = getUseMeItemMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type changeMeWeaponResponse204 = {
  data: void
  status: 204
}

export type changeMeWeaponResponse400 = {
  data: ErrorResponse
  status: 400
}

export type changeMeWeaponResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type changeMeWeaponResponseSuccess = (changeMeWeaponResponse204) & {
  headers: Headers;
};
export type changeMeWeaponResponseError = (changeMeWeaponResponse400 | changeMeWeaponResponse401) & {
  headers: Headers;
};

export type changeMeWeaponResponse = (changeMeWeaponResponseSuccess | changeMeWeaponResponseError)

export const getChangeMeWeaponUrl = () => {




  return `http://localhost:8085/actions/change-weapons`
}

/**
 * @summary 装備武器変更
 */
export const changeMeWeapon = async (changeWeaponRequest: ChangeWeaponRequest, options?: RequestInit): Promise<changeMeWeaponResponse> => {

  const res = await fetch(getChangeMeWeaponUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(changeWeaponRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: changeMeWeaponResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as changeMeWeaponResponse
}




export const getChangeMeWeaponMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ChangeWeaponRequest }) => {
    return changeMeWeapon(arg, options);
  }
}
export const getChangeMeWeaponMutationKey = () => [`http://localhost:8085/actions/change-weapons`] as const;

export type ChangeMeWeaponMutationResult = NonNullable<Awaited<ReturnType<typeof changeMeWeapon>>>

/**
 * @summary 装備武器変更
 */
export const useChangeMeWeapon = <TError = Promise<ErrorResponse | UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof changeMeWeapon>>, TError, Key, ChangeWeaponRequest, Awaited<ReturnType<typeof changeMeWeapon>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getChangeMeWeaponMutationKey();
  const swrFn = getChangeMeWeaponMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
