/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  UnauthorizedResponse,
  UploadImage200,
  UploadImageBody
} from '../bunkasaiRPGAPI.schemas';






 export type uploadImageResponse200 = {
  data: UploadImage200
  status: 200
}

export type uploadImageResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type uploadImageResponseSuccess = (uploadImageResponse200) & {
  headers: Headers;
};
export type uploadImageResponseError = (uploadImageResponse401) & {
  headers: Headers;
};

export type uploadImageResponse = (uploadImageResponseSuccess | uploadImageResponseError)

export const getUploadImageUrl = () => {




  return `http://localhost:8085/images`
}

/**
 * @summary 画像アップロード
 */
export const uploadImage = async (uploadImageBody: UploadImageBody, options?: RequestInit): Promise<uploadImageResponse> => {
    const formData = new FormData();
formData.append(`imageFile`, uploadImageBody.imageFile);
formData.append(`directory`, uploadImageBody.directory);

  const res = await fetch(getUploadImageUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadImageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadImageResponse
}




export const getUploadImageMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UploadImageBody }) => {
    return uploadImage(arg, options);
  }
}
export const getUploadImageMutationKey = () => [`http://localhost:8085/images`] as const;

export type UploadImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadImage>>>

/**
 * @summary 画像アップロード
 */
export const useUploadImage = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof uploadImage>>, TError, Key, UploadImageBody, Awaited<ReturnType<typeof uploadImage>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUploadImageMutationKey();
  const swrFn = getUploadImageMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
