/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  HealthCheck200
} from '../bunkasaiRPGAPI.schemas';






 export type healthCheckResponse200 = {
  data: HealthCheck200
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/health`
}

/**
 * @summary ヘルスチェック
 */
export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {

  const res = await fetch(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthCheckResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthCheckResponse
}




export const getHealthCheckKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/health`] as const;

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>

/**
 * @summary ヘルスチェック
 */
export const useHealthCheck = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof healthCheck>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getHealthCheckKey() : null);
  const swrFn = () => healthCheck(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
