/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetMeWeaponIndex200,
  GetMeWeaponIndexParams,
  GetWeaponIds200,
  GetWeapons200,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getWeaponsResponse200 = {
  data: GetWeapons200
  status: 200
}

export type getWeaponsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWeaponsResponseSuccess = (getWeaponsResponse200) & {
  headers: Headers;
};
export type getWeaponsResponseError = (getWeaponsResponse401) & {
  headers: Headers;
};

export type getWeaponsResponse = (getWeaponsResponseSuccess | getWeaponsResponseError)

export const getGetWeaponsUrl = () => {




  return `http://localhost:8085/weapons`
}

/**
 * @summary 所持武器一覧取得
 */
export const getWeapons = async ( options?: RequestInit): Promise<getWeaponsResponse> => {

  const res = await fetch(getGetWeaponsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWeaponsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWeaponsResponse
}




export const getGetWeaponsKey = () => [`http://localhost:8085/weapons`] as const;

export type GetWeaponsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeapons>>>

/**
 * @summary 所持武器一覧取得
 */
export const useGetWeapons = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWeapons>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWeaponsKey() : null);
  const swrFn = () => getWeapons(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMeWeaponIndexResponse200 = {
  data: GetMeWeaponIndex200
  status: 200
}

export type getMeWeaponIndexResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeWeaponIndexResponseSuccess = (getMeWeaponIndexResponse200) & {
  headers: Headers;
};
export type getMeWeaponIndexResponseError = (getMeWeaponIndexResponse401) & {
  headers: Headers;
};

export type getMeWeaponIndexResponse = (getMeWeaponIndexResponseSuccess | getMeWeaponIndexResponseError)

export const getGetMeWeaponIndexUrl = (params?: GetMeWeaponIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/weapons/index?${stringifiedParams}` : `http://localhost:8085/weapons/index`
}

/**
 * @summary 武器図鑑取得
 */
export const getMeWeaponIndex = async (params?: GetMeWeaponIndexParams, options?: RequestInit): Promise<getMeWeaponIndexResponse> => {

  const res = await fetch(getGetMeWeaponIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeWeaponIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeWeaponIndexResponse
}




export const getGetMeWeaponIndexKey = (params?: GetMeWeaponIndexParams,) => [`http://localhost:8085/weapons/index`, ...(params ? [params]: [])] as const;

export type GetMeWeaponIndexQueryResult = NonNullable<Awaited<ReturnType<typeof getMeWeaponIndex>>>

/**
 * @summary 武器図鑑取得
 */
export const useGetMeWeaponIndex = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMeWeaponIndexParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMeWeaponIndex>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMeWeaponIndexKey(params) : null);
  const swrFn = () => getMeWeaponIndex(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getWeaponIdsResponse200 = {
  data: GetWeaponIds200
  status: 200
}

export type getWeaponIdsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWeaponIdsResponseSuccess = (getWeaponIdsResponse200) & {
  headers: Headers;
};
export type getWeaponIdsResponseError = (getWeaponIdsResponse401) & {
  headers: Headers;
};

export type getWeaponIdsResponse = (getWeaponIdsResponseSuccess | getWeaponIdsResponseError)

export const getGetWeaponIdsUrl = () => {




  return `http://localhost:8085/weapons/ids`
}

/**
 * @summary [管理者専用] 全武器ID一覧取得
 */
export const getWeaponIds = async ( options?: RequestInit): Promise<getWeaponIdsResponse> => {

  const res = await fetch(getGetWeaponIdsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWeaponIdsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWeaponIdsResponse
}




export const getGetWeaponIdsKey = () => [`http://localhost:8085/weapons/ids`] as const;

export type GetWeaponIdsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeaponIds>>>

/**
 * @summary [管理者専用] 全武器ID一覧取得
 */
export const useGetWeaponIds = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWeaponIds>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWeaponIdsKey() : null);
  const swrFn = () => getWeaponIds(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
