/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetMeWeaponIndex200,
  GetMeWeaponIndexParams,
  GetWeaponSummaries200,
  GetWeapons200,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getWeaponsResponse200 = {
  data: GetWeapons200
  status: 200
}

export type getWeaponsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWeaponsResponseSuccess = (getWeaponsResponse200) & {
  headers: Headers;
};
export type getWeaponsResponseError = (getWeaponsResponse401) & {
  headers: Headers;
};

export type getWeaponsResponse = (getWeaponsResponseSuccess | getWeaponsResponseError)

export const getGetWeaponsUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/weapons`
}

/**
 * @summary 所持武器一覧取得
 */
export const getWeapons = async ( options?: RequestInit): Promise<getWeaponsResponse> => {

  const res = await fetch(getGetWeaponsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWeaponsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWeaponsResponse
}




export const getGetWeaponsKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/weapons`] as const;

export type GetWeaponsQueryResult = NonNullable<Awaited<ReturnType<typeof getWeapons>>>

/**
 * @summary 所持武器一覧取得
 */
export const useGetWeapons = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWeapons>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWeaponsKey() : null);
  const swrFn = () => getWeapons(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMeWeaponIndexResponse200 = {
  data: GetMeWeaponIndex200
  status: 200
}

export type getMeWeaponIndexResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeWeaponIndexResponseSuccess = (getMeWeaponIndexResponse200) & {
  headers: Headers;
};
export type getMeWeaponIndexResponseError = (getMeWeaponIndexResponse401) & {
  headers: Headers;
};

export type getMeWeaponIndexResponse = (getMeWeaponIndexResponseSuccess | getMeWeaponIndexResponseError)

export const getGetMeWeaponIndexUrl = (params?: GetMeWeaponIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL}/weapons/index?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL}/weapons/index`
}

/**
 * @summary 武器図鑑取得
 */
export const getMeWeaponIndex = async (params?: GetMeWeaponIndexParams, options?: RequestInit): Promise<getMeWeaponIndexResponse> => {

  const res = await fetch(getGetMeWeaponIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeWeaponIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeWeaponIndexResponse
}




export const getGetMeWeaponIndexKey = (params?: GetMeWeaponIndexParams,) => [`${process.env.NEXT_PUBLIC_API_URL}/weapons/index`, ...(params ? [params]: [])] as const;

export type GetMeWeaponIndexQueryResult = NonNullable<Awaited<ReturnType<typeof getMeWeaponIndex>>>

/**
 * @summary 武器図鑑取得
 */
export const useGetMeWeaponIndex = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMeWeaponIndexParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMeWeaponIndex>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMeWeaponIndexKey(params) : null);
  const swrFn = () => getMeWeaponIndex(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getWeaponSummariesResponse200 = {
  data: GetWeaponSummaries200
  status: 200
}

export type getWeaponSummariesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getWeaponSummariesResponseSuccess = (getWeaponSummariesResponse200) & {
  headers: Headers;
};
export type getWeaponSummariesResponseError = (getWeaponSummariesResponse401) & {
  headers: Headers;
};

export type getWeaponSummariesResponse = (getWeaponSummariesResponseSuccess | getWeaponSummariesResponseError)

export const getGetWeaponSummariesUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/weapons/summaries`
}

/**
 * マスタに登録されている全武器を図鑑番号の昇順で返す。管理画面が
 * 「何が存在するか」を把握するために使う。どの画像を割り当てるかは
 * フロント側の関心なので、ここでは画像情報は一切返さない。
 * @summary [管理者専用] 全武器の一覧取得
 */
export const getWeaponSummaries = async ( options?: RequestInit): Promise<getWeaponSummariesResponse> => {

  const res = await fetch(getGetWeaponSummariesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWeaponSummariesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWeaponSummariesResponse
}




export const getGetWeaponSummariesKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/weapons/summaries`] as const;

export type GetWeaponSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof getWeaponSummaries>>>

/**
 * @summary [管理者専用] 全武器の一覧取得
 */
export const useGetWeaponSummaries = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getWeaponSummaries>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetWeaponSummariesKey() : null);
  const swrFn = () => getWeaponSummaries(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
