/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AdminLoginRequest,
  AuthResponse,
  ErrorResponse,
  UserLoginRequest
} from '../bunkasaiRPGAPI.schemas';






 export type userLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type userLoginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type userLoginResponseSuccess = (userLoginResponse200) & {
  headers: Headers;
};
export type userLoginResponseError = (userLoginResponse401) & {
  headers: Headers;
};

export type userLoginResponse = (userLoginResponseSuccess | userLoginResponseError)

export const getUserLoginUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/auth/user-login`
}

/**
 * @summary ユーザーログイン
 */
export const userLogin = async (userLoginRequest: UserLoginRequest, options?: RequestInit): Promise<userLoginResponse> => {

  const res = await fetch(getUserLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userLoginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as userLoginResponse
}




export const getUserLoginMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UserLoginRequest }) => {
    return userLogin(arg, options);
  }
}
export const getUserLoginMutationKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/auth/user-login`] as const;

export type UserLoginMutationResult = NonNullable<Awaited<ReturnType<typeof userLogin>>>

/**
 * @summary ユーザーログイン
 */
export const useUserLogin = <TError = Promise<ErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof userLogin>>, TError, Key, UserLoginRequest, Awaited<ReturnType<typeof userLogin>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUserLoginMutationKey();
  const swrFn = getUserLoginMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type adminLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type adminLoginResponse401 = {
  data: ErrorResponse
  status: 401
}

export type adminLoginResponseSuccess = (adminLoginResponse200) & {
  headers: Headers;
};
export type adminLoginResponseError = (adminLoginResponse401) & {
  headers: Headers;
};

export type adminLoginResponse = (adminLoginResponseSuccess | adminLoginResponseError)

export const getAdminLoginUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/auth/admin-login`
}

/**
 * @summary 管理者ログイン
 */
export const adminLogin = async (adminLoginRequest: AdminLoginRequest, options?: RequestInit): Promise<adminLoginResponse> => {

  const res = await fetch(getAdminLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminLoginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: adminLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminLoginResponse
}




export const getAdminLoginMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: AdminLoginRequest }) => {
    return adminLogin(arg, options);
  }
}
export const getAdminLoginMutationKey = () => [`${process.env.NEXT_PUBLIC_API_URL}/auth/admin-login`] as const;

export type AdminLoginMutationResult = NonNullable<Awaited<ReturnType<typeof adminLogin>>>

/**
 * @summary 管理者ログイン
 */
export const useAdminLogin = <TError = Promise<ErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof adminLogin>>, TError, Key, AdminLoginRequest, Awaited<ReturnType<typeof adminLogin>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAdminLoginMutationKey();
  const swrFn = getAdminLoginMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
