/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetItemIds200,
  GetItems200,
  GetMeItemIndex200,
  GetMeItemIndexParams,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getItemsResponse200 = {
  data: GetItems200
  status: 200
}

export type getItemsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getItemsResponseSuccess = (getItemsResponse200) & {
  headers: Headers;
};
export type getItemsResponseError = (getItemsResponse401) & {
  headers: Headers;
};

export type getItemsResponse = (getItemsResponseSuccess | getItemsResponseError)

export const getGetItemsUrl = () => {




  return `http://localhost:8085/items`
}

/**
 * @summary 所持アイテム一覧取得
 */
export const getItems = async ( options?: RequestInit): Promise<getItemsResponse> => {

  const res = await fetch(getGetItemsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getItemsResponse
}




export const getGetItemsKey = () => [`http://localhost:8085/items`] as const;

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>

/**
 * @summary 所持アイテム一覧取得
 */
export const useGetItems = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getItems>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetItemsKey() : null);
  const swrFn = () => getItems(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMeItemIndexResponse200 = {
  data: GetMeItemIndex200
  status: 200
}

export type getMeItemIndexResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeItemIndexResponseSuccess = (getMeItemIndexResponse200) & {
  headers: Headers;
};
export type getMeItemIndexResponseError = (getMeItemIndexResponse401) & {
  headers: Headers;
};

export type getMeItemIndexResponse = (getMeItemIndexResponseSuccess | getMeItemIndexResponseError)

export const getGetMeItemIndexUrl = (params?: GetMeItemIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/items/index?${stringifiedParams}` : `http://localhost:8085/items/index`
}

/**
 * @summary アイテム図鑑取得
 */
export const getMeItemIndex = async (params?: GetMeItemIndexParams, options?: RequestInit): Promise<getMeItemIndexResponse> => {

  const res = await fetch(getGetMeItemIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeItemIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeItemIndexResponse
}




export const getGetMeItemIndexKey = (params?: GetMeItemIndexParams,) => [`http://localhost:8085/items/index`, ...(params ? [params]: [])] as const;

export type GetMeItemIndexQueryResult = NonNullable<Awaited<ReturnType<typeof getMeItemIndex>>>

/**
 * @summary アイテム図鑑取得
 */
export const useGetMeItemIndex = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMeItemIndexParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMeItemIndex>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMeItemIndexKey(params) : null);
  const swrFn = () => getMeItemIndex(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getItemIdsResponse200 = {
  data: GetItemIds200
  status: 200
}

export type getItemIdsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getItemIdsResponseSuccess = (getItemIdsResponse200) & {
  headers: Headers;
};
export type getItemIdsResponseError = (getItemIdsResponse401) & {
  headers: Headers;
};

export type getItemIdsResponse = (getItemIdsResponseSuccess | getItemIdsResponseError)

export const getGetItemIdsUrl = () => {




  return `http://localhost:8085/items/ids`
}

/**
 * @summary [管理者専用] 全アイテムID一覧取得
 */
export const getItemIds = async ( options?: RequestInit): Promise<getItemIdsResponse> => {

  const res = await fetch(getGetItemIdsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getItemIdsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getItemIdsResponse
}




export const getGetItemIdsKey = () => [`http://localhost:8085/items/ids`] as const;

export type GetItemIdsQueryResult = NonNullable<Awaited<ReturnType<typeof getItemIds>>>

/**
 * @summary [管理者専用] 全アイテムID一覧取得
 */
export const useGetItemIds = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getItemIds>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetItemIdsKey() : null);
  const swrFn = () => getItemIds(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
