/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Bunkasai RPG API
 * 文化祭RPG API
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetItemSummaries200,
  GetItems200,
  GetMeItemIndex200,
  GetMeItemIndexParams,
  UnauthorizedResponse
} from '../bunkasaiRPGAPI.schemas';






 export type getItemsResponse200 = {
  data: GetItems200
  status: 200
}

export type getItemsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getItemsResponseSuccess = (getItemsResponse200) & {
  headers: Headers;
};
export type getItemsResponseError = (getItemsResponse401) & {
  headers: Headers;
};

export type getItemsResponse = (getItemsResponseSuccess | getItemsResponseError)

export const getGetItemsUrl = () => {




  return `http://localhost:8085/items`
}

/**
 * @summary 所持アイテム一覧取得
 */
export const getItems = async ( options?: RequestInit): Promise<getItemsResponse> => {

  const res = await fetch(getGetItemsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getItemsResponse
}




export const getGetItemsKey = () => [`http://localhost:8085/items`] as const;

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>

/**
 * @summary 所持アイテム一覧取得
 */
export const useGetItems = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getItems>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetItemsKey() : null);
  const swrFn = () => getItems(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getMeItemIndexResponse200 = {
  data: GetMeItemIndex200
  status: 200
}

export type getMeItemIndexResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMeItemIndexResponseSuccess = (getMeItemIndexResponse200) & {
  headers: Headers;
};
export type getMeItemIndexResponseError = (getMeItemIndexResponse401) & {
  headers: Headers;
};

export type getMeItemIndexResponse = (getMeItemIndexResponseSuccess | getMeItemIndexResponseError)

export const getGetMeItemIndexUrl = (params?: GetMeItemIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/items/index?${stringifiedParams}` : `http://localhost:8085/items/index`
}

/**
 * @summary アイテム図鑑取得
 */
export const getMeItemIndex = async (params?: GetMeItemIndexParams, options?: RequestInit): Promise<getMeItemIndexResponse> => {

  const res = await fetch(getGetMeItemIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeItemIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeItemIndexResponse
}




export const getGetMeItemIndexKey = (params?: GetMeItemIndexParams,) => [`http://localhost:8085/items/index`, ...(params ? [params]: [])] as const;

export type GetMeItemIndexQueryResult = NonNullable<Awaited<ReturnType<typeof getMeItemIndex>>>

/**
 * @summary アイテム図鑑取得
 */
export const useGetMeItemIndex = <TError = Promise<UnauthorizedResponse>>(
  params?: GetMeItemIndexParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getMeItemIndex>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetMeItemIndexKey(params) : null);
  const swrFn = () => getMeItemIndex(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getItemSummariesResponse200 = {
  data: GetItemSummaries200
  status: 200
}

export type getItemSummariesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getItemSummariesResponseSuccess = (getItemSummariesResponse200) & {
  headers: Headers;
};
export type getItemSummariesResponseError = (getItemSummariesResponse401) & {
  headers: Headers;
};

export type getItemSummariesResponse = (getItemSummariesResponseSuccess | getItemSummariesResponseError)

export const getGetItemSummariesUrl = () => {




  return `http://localhost:8085/items/summaries`
}

/**
 * マスタに登録されている全アイテムを図鑑番号の昇順で返す。管理画面が
 * 「何が存在するか」を把握するために使う。どの画像を割り当てるかは
 * フロント側の関心なので、ここでは画像情報は一切返さない。
 * @summary [管理者専用] 全アイテムの一覧取得
 */
export const getItemSummaries = async ( options?: RequestInit): Promise<getItemSummariesResponse> => {

  const res = await fetch(getGetItemSummariesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getItemSummariesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getItemSummariesResponse
}




export const getGetItemSummariesKey = () => [`http://localhost:8085/items/summaries`] as const;

export type GetItemSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof getItemSummaries>>>

/**
 * @summary [管理者専用] 全アイテムの一覧取得
 */
export const useGetItemSummaries = <TError = Promise<UnauthorizedResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getItemSummaries>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetItemSummariesKey() : null);
  const swrFn = () => getItemSummaries(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
